### ISSUE TITLE
Hawaii-shell fails to build on Ubuntu 15.04

### ISSUE THREAD

**Issue by n3rdopolis** [hawaii-desktop/hawaii-shell#167]
It seems that pa_channels_valid was added in PuiseAudio 5, and even Ubuntu 15.04 is stuck at PulseAudio 4.0

 49%] Building CXX object 3rdparty/libqtxdg/CMakeFiles/HawaiiQtXDG.dir/desktopenvironment_p.cpp.o
/srcbuild/hawaii-shell/declarative/mixer/pulseaudiomixerbackend.cpp: In member function ‘virtual void PulseAudioMixerBackend::setVolume(int)’:
/srcbuild/hawaii-shell/declarative/mixer/pulseaudiomixerbackend.cpp:192:50: error: ‘pa_channels_valid’ was not declared in this scope
     if (pa_channels_valid(m_sink->volume.channels)) {
                                                  ^
declarative/mixer/CMakeFiles/mixerplugin.dir/build.make:123: recipe for target 'declarative/mixer/CMakeFiles/mixerplugin.dir/pulseaudiomixerbackend.cpp.o' failed
make[2]: *** [declarative/mixer/CMakeFiles/mixerplugin.dir/pulseaudiomixerbackend.cpp.o] Error 1
CMakeFiles/Makefile2:635: recipe for target 'declarative/mixer/CMakeFiles/mixerplugin.dir/all' failed
make[1]: *** [declarative/mixer/CMakeFiles/mixerplugin.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 50%] Building CXX object 3rdparty/libqtxdg/CMakeFiles/HawaiiQtXDG.dir/HawaiiQtXDG_automoc.cpp.o
[ 52%] Building CXX object framework/themes/CMakeFiles/declarative_hawaiithemes.dir/themesettings.cpp.o
[ 54%] Building CXX object framework/themes/CMakeFiles/declarative_hawaiithemes.dir/declarative_hawaiithemes_automoc.cpp.o
[ 55%] Building CXX object platformtheme/CMakeFiles/HawaiiPlatformTheme.dir/hawaiitheme.cpp.o
Linking CXX static library libHawaiiQtXDG.a
[ 55%] Built target HawaiiQtXDG
[ 57%] Building CXX object platformtheme/CMakeFiles/HawaiiPlatformTheme.dir/HawaiiPlatformTheme_automoc.cpp.o
Linking CXX shared library libdeclarative_hawaiithemes.so
[ 57%] Built target declarative_hawaiithemes
Linking CXX shared library HawaiiPlatformTheme.so
[ 57%] Built target HawaiiPlatformTheme
Makefile:147: recipe for target 'all' failed
make: *** [all] Error 2
PackageCompileSource finished in 33 seconds

**Comment by plfiorini** [comment]
Using Arch doesn't help :)

**Comment by plfiorini** [comment]
Does it fix the issue?

**Comment by n3rdopolis** [comment]
Seems to fix it, but it seems I have to workaround the include directory issues that I reported, and it looks like commit 14d315eaa7b8c7c2c60a701585ee913625b96854 make it not find <QtGui>
But I think this paticular issue is fixed, I wlll keep you updated. Thanks.

**Comment by n3rdopolis** [comment]
This fixes it.
Thanks.
